/*
 * Created on 2017-03-22 ( Date ISO 2017-03-22 - Time 16:41:52 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */

package org.demo.data.record;


import org.junit.Assert;
import org.junit.Test;
import java.util.logging.*;

/**
 * JUnit test case for bean CountryRecord
 * 
 * @author Telosys Tools Generator
 *
 */
public class CountryRecordTest 
{
	private static final Logger LOGGER = Logger.getLogger(CountryRecordTest.class.getName());
	@Test
	public void testSettersAndGetters() {
		
		LOGGER.info("Checking class CountryRecord getters and setters ..." );
		
		CountryRecord countryRecord = new CountryRecord();


		//--- Test setter/getter for attribute "code"  ( model type : String / wrapperType : String )
		countryRecord.setCode( "AA" ) ;
		Assert.assertEquals( "AA", countryRecord.getCode() ) ; // Not primitive type in model


		//--- Test setter/getter for attribute "name"  ( model type : String / wrapperType : String )
		countryRecord.setName( "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" ) ;
		Assert.assertEquals( "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", countryRecord.getName() ) ; // Not primitive type in model


	}

}
