/*
 * Created on 2017-03-22 ( Date ISO 2017-03-22 - Time 16:15:26 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */
package org.demo.data.record.listitem;

import org.demo.data.record.CarRecord;
import org.demo.commons.ListItem;

public class CarListItem implements ListItem {

	private final String value ;
	private final String label ;
	
	public CarListItem(CarRecord car) {
		super();

		this.value = ""
			 + car.getId()
		;

		//TODO : Define here the attributes to be displayed as the label
		this.label = car.toString();
	}

	//@Override
	public String getValue() {
		return value;
	}

	//@Override
	public String getLabel() {
		return label;
	}

}
