/*
 * Created on 2017-03-22 ( Date ISO 2017-03-22 - Time 16:41:53 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */
package org.demo.data.record.listitem;

import org.demo.data.record.ReviewRecord;
import org.demo.commons.ListItem;

public class ReviewListItem implements ListItem {

	private final String value ;
	private final String label ;
	
	public ReviewListItem(ReviewRecord review) {
		super();

		this.value = ""
			 + review.getCustomerCode()
			 + "|"  + review.getBookId()
		;

		//TODO : Define here the attributes to be displayed as the label
		this.label = review.toString();
	}

	//@Override
	public String getValue() {
		return value;
	}

	//@Override
	public String getLabel() {
		return label;
	}

}
