/*
 * Created on 2017-03-22 ( Date ISO 2017-03-22 - Time 16:41:52 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */
package org.demo.persistence.impl.mongo;

import java.util.List;
import javax.inject.Named;
import org.bson.conversions.Bson;
import org.demo.persistence.impl.mongo.commons.GenericMongoDAO;
import org.bson.Document;
import org.demo.persistence.impl.mongo.commons.DocumentWrapper;



import org.demo.data.record.CountryRecord;
import org.demo.persistence.CountryPersistence;

@Named("CountryPersistence")
public class CountryPersistenceImplMongo extends GenericMongoDAO<CountryRecord> implements CountryPersistence {

	/**
	 * DAO constructor
	 */
	public CountryPersistenceImplMongo() {
		super("country");
	}

	/**
	 * Creates a new instance of the bean
	 * primary value(s)
	 * 
	 * @param key;
	 * @return the new instance
	 */
	private CountryRecord newInstanceWithPrimaryKey(String code) {
		CountryRecord country = new CountryRecord ();
        country.setCode(code); 
		return country;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see interface
	 */
	public CountryRecord findById(String code){
        CountryRecord  country = newInstanceWithPrimaryKey(code);
		return super.doSelect(country);
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see interface
	 */
	public List<CountryRecord> findAll() {
		return super.doSelectAll();
	}

	/**
	 * Loads the given bean, it is supposed to contains the primary key value(s)
	 * in its attribute(s)<br>
	 * If found, the given instance is populated with the values retrieved from
	 * the database<br>
	 * If not found, the given instance remains unchanged
	 */
	public CountryRecord load(CountryRecord country) {
		 return super.doSelect(country);
	}

	/**
	 * Inserts the given bean in the database
	 * 
	 */
	public   void   insert(CountryRecord country){
		 super.doInsert(country);
	}
	/*
	 * (non-Javadoc)
	 * 
	 * @see interface
	 */
	public void save(CountryRecord country){
		if (super.doExists(country)) {
			super.doUpdate(country);
		} else {
			insert(country);
		}
	}
	/*
	 * (non-Javadoc)
	 * 
	 * @see interface
	 */
	public boolean update(CountryRecord country){
		long result= super.doUpdate(country);	
		return result > 0L;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see interface
	 */
public 	CountryRecord   create(CountryRecord country){
		insert(country);
        return country;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see interface
	 */
	public boolean deleteById(String code) {
		CountryRecord country = newInstanceWithPrimaryKey(code);
		long r = super.doDelete(country);
		return r > 0L;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see interface
	 */
	public boolean delete(CountryRecord country) {
		long r = super.doDelete(country);
		return r > 0L;
	}

	/**
	 * Checks the existence of a record in the database using the given primary
	 * key value(s)
	 * @return
	 */
	public boolean exists(String code) {
		CountryRecord country = newInstanceWithPrimaryKey(code);
		return super.doExists(country);
	}

	/**
	 * Checks the existence of the given bean in the database
	 * @return
	 */
	public boolean exists(CountryRecord country) {
		return super.doExists(country);
	}

	/**
	 * Counts all the records present in the database
	 * 
	 * @return
	 */
	public long countAll() {
		return super.doCountAll();
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see Abstract Class
	 */
	@Override
	protected CountryRecord docTobean(Document doc) {
		CountryRecord country = new CountryRecord ();
		DocumentWrapper mongoDoc = new DocumentWrapper(doc);
		//--- Set data from document to Bean attributes
		country.setCode(mongoDoc.getString("code"));
		country.setName(mongoDoc.getString("name"));
		return country ;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see Abstract Class
	 */
	@Override
	protected DocumentWrapper beanToDoc(CountryRecord  bean) {
		//--- Set data from bean to Document attributes
		DocumentWrapper doc = new DocumentWrapper();	
		doc.append("code", bean.getCode());
		doc.append("name", bean.getName());
		return doc; 
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see Abstract Class
	 */
	@Override
	protected void setAutoIncrementedKey(CountryRecord  bean, long id) {
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see Abstract Class
	 */
	@Override
	protected Bson bsonForIdentifyBean(CountryRecord  bean) {
		DocumentWrapper mongoDoc = new DocumentWrapper();
		mongoDoc.append("code", bean.getCode());
		return	mongoDoc.getDocument();
	}

}
